### ISSUE TITLE
python container error

### ISSUE THREAD

**Issue by camiloariza** [nettoyoussef/science-reproducibility#1]
Hi,

I was having a trouble getting the containers up!

The jupyter server wasn't initializing properly! I think it was because the `docker-compose.yml` was not setting the command properly.

I fixed this issue like this:

```diff
--- a/Dockerfiles/docker-compose.yml
+++ b/Dockerfiles/docker-compose.yml
@@ -15,18 +15,18 @@ services:
     environment:
       - JUPYTER_TOKEN=${JUPYTER_PASSWORD}
     command:
-      jupyter notebook --port=8888 --no-browser --ip=0.0.0.0 --allow-root --notebook-dir=/home/science-repro
+      jupyter notebook --port=8888 --no-browser --ip=0.0.0.0 --allow-root --notebook-dir=/home/${LOGIN_USER}/
```

Is this the proper way to get things work?

Thank you in advance. See you later!

**Comment by nettoyoussef** [comment]
Hi Camilo,

Thanks, you are correct! I will update the repo.
